version: '3'
services:
  blog:
    # restart: always
    image: toads/tblog
    volumes:
      - blog-static:/usr/src/app/Tblog/static
    env_file: .env
    networks:
      - webnet


  blog-proxy:
    # restart: always
    image: nginx:stable-alpine
    ports:
      - "20022:80"
      - "20024:443"
    volumes:
      - /etc/letsencrypt/live/toads.me/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/toads.me/privkey.pem:/etc/nginx/privkey.pem
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - blog-static:/usr/share/nginx/html/static:ro
      - blog-static:/usr/share/nginx/html/media:ro
    networks:
      - webnet

volumes:
  blog-static:
networks:
  webnet:
